language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install coveralls
  - python setup.py install
script:
  - coverage run setup.py test
after_success:
  - coveralls
