#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

from link.graph.dsl.generator import single_parser_per_scope
from argparse import ArgumentParser
import json


if __name__ == '__main__':
    aparser = ArgumentParser(description='Parse GraphDSL requests')
    aparser.add_argument(
        '-f', '--file', nargs=1, required=True, help='request file'
    )

    args = aparser.parse_args()

    module = single_parser_per_scope()
    parser = module.GraphDSLParser()

    for fname in args.file:
        print('-' * 80)

        print('File: {0}'.format(fname))
        print()

        with open(fname) as f:
            content = f.read()

        ast = parser.parse(content, 'start')

        print('AST:')
        print(ast)
        print()

        print('JSON:')
        print(json.dumps(ast, indent=2))
        print()
