#!/usr/bin/env python
# -*- coding: utf-8 -*-

from link.graph.dsl.lexer import GraphDSLLexer
from link.graph.core import GraphManager
from link.graph import __version__

from prompt_toolkit.key_binding.manager import KeyBindingManager
from prompt_toolkit.layout.lexers import PygmentsLexer
from prompt_toolkit.token import Token
from prompt_toolkit.keys import Keys
from prompt_toolkit import prompt
from six import print_


class GraphCLI(object):
    def __init__(self, *args, **kwargs):
        super(GraphCLI, self).__init__(*args, **kwargs)

        self.graph = GraphManager()
        self.kbmgr = KeyBindingManager.for_prompt()

        self.register_shortcuts()

    def register_shortcuts(self):
        self.kbmgr.registry.add_binding(Keys.ControlJ)(self.newline_or_execute)
        self.kbmgr.registry.add_binding(Keys.ControlC)(self.cancel_input)

    def newline_or_execute(self, event):
        buf = event.current_buffer
        doc = buf.document

        if buf.complete_state:
            compl = buf.complete_state.current_completion

            if compl:
                buf.apply_completion(compl)

            else:
                buf.cancel_completion()

        text = doc.text.strip()

        if len(text) > 0 and text[-1] == ';':
            buf.accept_action.validate_and_handle(event.cli, buf)

        else:
            buf.newline()

    def cancel_input(self, event):
        buf = event.current_buffer

        if buf.complete_state:
            buf.cancel_completion()

        else:
            buf.reset()

    def get_title(self):
        return 'GraphCLI v{0}'.format(__version__)

    def continuation_tokens(self, cli, width):
        return [
            (Token, '.' * (width - 1) + ' ')
        ]

    def __call__(self):
        print_(self.get_title())

        while True:
            try:
                request = prompt(
                    '>>> ',
                    multiline=True,
                    get_title=self.get_title,
                    get_continuation_tokens=self.continuation_tokens,
                    key_bindings_registry=self.kbmgr.registry,
                    lexer=PygmentsLexer(GraphDSLLexer)
                )

                request = request.strip()[:-1]
                result = self.graph(request)
                print(result)

            except EOFError:
                break

        print_('Goodbye!')


if __name__ == '__main__':
    cli = GraphCLI()
    cli()
