#!/usr/bin/env python
# -*- coding: utf-8 -*-

from link.graph.cli.core import GraphCLI
from argparse import ArgumentParser


if __name__ == '__main__':
    parser = ArgumentParser(description='Graph Command Line Interface')
    parser.add_argument('-U', default='graph://', help='Graph Middleware URL')
    args = parser.parse_args()

    cli = GraphCLI(args.U)
    cli()
